version: '3.8'

services:

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: always
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--api-port=3000"

volumes:
  mysql_data:
