"""add invoices reconciliation and limits

Revision ID: 15863dc71268
Revises: 832c883595c3
Create Date: 2026-05-27 23:30:25.609565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15863dc71268'
down_revision: Union[str, None] = '832c883595c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    columns = {col["name"] for col in inspector.get_columns("invoice_line_items")}
    if "verified" not in columns:
        op.add_column('invoice_line_items', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        op.alter_column('invoice_line_items', 'verified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_line_items', 'verified')
    # ### end Alembic commands ###
