"""added reletationship between User(Technician) and Pharmacy

Revision ID: 2a898550855b
Revises: b20aadc4505e
Create Date: 2026-03-13 15:18:07.280763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a898550855b'
down_revision: Union[str, None] = 'b20aadc4505e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pharmacy_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'PHARMACY_OWNER', 'TECHNICIAN'),
               type_=sa.Enum('PHARMACY_OWNER', 'TECHNICIAN', 'ADMIN', name='userrole'),
               nullable=False)
    op.create_foreign_key(None, 'user', 'pharmacy', ['pharmacy_id'], ['pharmacy_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'role',
               existing_type=sa.Enum('PHARMACY_OWNER', 'TECHNICIAN', 'ADMIN', name='userrole'),
               type_=mysql.ENUM('ADMIN', 'PHARMACY_OWNER', 'TECHNICIAN'),
               nullable=True)
    op.drop_column('user', 'pharmacy_id')
    # ### end Alembic commands ###
