"""add_medicine_ndc_cache

Revision ID: 41f560f3a557
Revises: e10afcb860b5
Create Date: 2026-06-13 00:46:13.790955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41f560f3a557'
down_revision: Union[str, None] = 'e10afcb860b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_ndc_cache',
    sa.Column('ndc11', sa.String(length=11), nullable=False),
    sa.Column('matched_package_ndc', sa.String(length=20), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('generic_name', sa.String(length=500), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('marketing_category', sa.String(length=50), nullable=True),
    sa.Column('marketing_start_date', sa.String(length=8), nullable=True),
    sa.Column('marketing_end_date', sa.String(length=8), nullable=True),
    sa.Column('listing_expiration_date', sa.String(length=8), nullable=True),
    sa.Column('package_description', sa.Text(), nullable=True),
    sa.Column('is_unit_of_use', sa.Boolean(), nullable=False),
    sa.Column('found_in_fda', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ndc11')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_ndc_cache')
    # ### end Alembic commands ###
