"""Refrshed new migration after Address added

Revision ID: 470fc37b5f75
Revises: 
Create Date: 2026-04-29 10:33:17.287234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470fc37b5f75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_address_address_id'), 'address', ['address_id'], unique=False)
    op.create_table('drug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=200), nullable=True),
    sa.Column('pharmacy_address', sa.String(length=400), nullable=True),
    sa.Column('pharmacy_phone', sa.String(length=30), nullable=True),
    sa.Column('pharmacy_fax', sa.String(length=30), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('report_from_date', sa.String(length=20), nullable=True),
    sa.Column('report_to_date', sa.String(length=20), nullable=True),
    sa.Column('grand_total_rx_count', sa.Integer(), nullable=True),
    sa.Column('grand_total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PHARMACY_OWNER', 'TECHNICIAN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('pharmacy',
    sa.Column('pharmacy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pharmacy_id')
    )
    op.create_index(op.f('ix_pharmacy_pharmacy_id'), 'pharmacy', ['pharmacy_id'], unique=False)
    op.create_foreign_key('fk_user_pharmacy_id', 'user', 'pharmacy', ['pharmacy_id'], ['pharmacy_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=300), nullable=False),
    sa.Column('ndc', sa.String(length=11), nullable=False),
    sa.Column('inventory_bucket', sa.String(length=100), nullable=True),
    sa.Column('lot_no_exp_date', sa.String(length=100), nullable=True),
    sa.Column('total_packs', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_rx_count', sa.Integer(), nullable=True),
    sa.Column('total_ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['drug_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_ndc'), 'medicines', ['ndc'], unique=False)
    op.create_index(op.f('ix_medicines_report_id'), 'medicines', ['report_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_refresh_token_id'), 'refresh_tokens', ['refresh_token_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('qty_disp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('qty_ord', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('date_filled', sa.String(length=12), nullable=True),
    sa.Column('rx_no', sa.String(length=20), nullable=True),
    sa.Column('ref', sa.String(length=10), nullable=True),
    sa.Column('pat_name', sa.String(length=200), nullable=True),
    sa.Column('pat_addr', sa.Text(), nullable=True),
    sa.Column('pat_phone', sa.String(length=30), nullable=True),
    sa.Column('pres_name', sa.String(length=200), nullable=True),
    sa.Column('pres_addr', sa.Text(), nullable=True),
    sa.Column('pres_phone', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_code', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispenses_medicine_id'), 'dispenses', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_dispenses_rx_no'), 'dispenses', ['rx_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispenses_rx_no'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_medicine_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_medicines_report_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_ndc'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_constraint('fk_user_pharmacy_id', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_pharmacy_pharmacy_id'), table_name='pharmacy')
    op.drop_table('pharmacy')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('drug_reports')
    op.drop_index(op.f('ix_address_address_id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
