"""add_stripe_payment_fields

Revision ID: 51b8d1ce7b01
Revises: f7a8b9c0d1e2
Create Date: 2026-07-19 15:16:44.718459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b8d1ce7b01'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('record_Identifier', sa.String(length=36), nullable=True),
    sa.Column('update_record_Identifier', sa.String(length=36), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('delete_date_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('global_time_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index('ix_subpay_ms_id_status', 'subscription_payments', ['medical_store_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscription_payments_medical_store_id'), 'subscription_payments', ['medical_store_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_payment_id'), 'subscription_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_record_Identifier'), 'subscription_payments', ['record_Identifier'], unique=False)
    op.create_index(op.f('ix_subscription_payments_status'), 'subscription_payments', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_update_record_Identifier'), 'subscription_payments', ['update_record_Identifier'], unique=False)
    op.drop_index(op.f('ix_activity_log_record_Identifier'), table_name='activity_log')
    op.create_index(op.f('ix_activity_log_record_Identifier'), 'activity_log', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_dispenses_record_Identifier'), table_name='dispenses')
    op.create_index(op.f('ix_dispenses_record_Identifier'), 'dispenses', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_documents_record_Identifier'), table_name='documents')
    op.create_index(op.f('ix_documents_record_Identifier'), 'documents', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_drug_reports_record_Identifier'), table_name='drug_reports')
    op.create_index(op.f('ix_drug_reports_record_Identifier'), 'drug_reports', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_invoice_line_items_record_Identifier'), table_name='invoice_line_items')
    op.create_index(op.f('ix_invoice_line_items_record_Identifier'), 'invoice_line_items', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_invoice_summaries_record_Identifier'), table_name='invoice_summaries')
    op.create_index(op.f('ix_invoice_summaries_record_Identifier'), 'invoice_summaries', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_invoices_record_Identifier'), table_name='invoices')
    op.create_index(op.f('ix_invoices_record_Identifier'), 'invoices', ['record_Identifier'], unique=False)
    op.add_column('medical_store', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('medical_store', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True, comment='Stripe Customer ID'))
    op.drop_index(op.f('ix_medical_store_record_Identifier'), table_name='medical_store')
    op.create_index(op.f('ix_medical_store_record_Identifier'), 'medical_store', ['record_Identifier'], unique=False)
    op.create_unique_constraint(None, 'medical_store', ['stripe_customer_id'])
    op.drop_index(op.f('ix_medicine_inventory_record_Identifier'), table_name='medicine_inventory')
    op.create_index(op.f('ix_medicine_inventory_record_Identifier'), 'medicine_inventory', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_medicine_ndc_cache_record_Identifier'), table_name='medicine_ndc_cache')
    op.create_index(op.f('ix_medicine_ndc_cache_record_Identifier'), 'medicine_ndc_cache', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_medicines_record_Identifier'), table_name='medicines')
    op.create_index(op.f('ix_medicines_record_Identifier'), 'medicines', ['record_Identifier'], unique=False)
    op.add_column('plans', sa.Column('stripe_product_id', sa.String(length=255), nullable=True, comment='Stripe Product ID'))
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(length=255), nullable=True, comment='Stripe Price ID (monthly recurring)'))
    op.drop_index(op.f('ix_plans_record_Identifier'), table_name='plans')
    op.create_index(op.f('ix_plans_record_Identifier'), 'plans', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_refill_dismissals_record_Identifier'), table_name='refill_dismissals')
    op.create_index(op.f('ix_refill_dismissals_record_Identifier'), 'refill_dismissals', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_record_Identifier'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_record_Identifier'), 'refresh_tokens', ['record_Identifier'], unique=False)
    op.drop_index(op.f('ix_subscription_events_record_Identifier'), table_name='subscription_events')
    op.create_index(op.f('ix_subscription_events_record_Identifier'), 'subscription_events', ['record_Identifier'], unique=False)
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True, comment='Stripe Subscription ID'))
    op.add_column('subscriptions', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True, comment='Pending Stripe Checkout Session'))
    op.drop_index(op.f('ix_subscriptions_record_Identifier'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_record_Identifier'), 'subscriptions', ['record_Identifier'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.drop_index(op.f('ix_user_record_Identifier'), table_name='user')
    op.create_index(op.f('ix_user_record_Identifier'), 'user', ['record_Identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_record_Identifier'), table_name='user')
    op.create_index(op.f('ix_user_record_Identifier'), 'user', ['record_Identifier'], unique=True)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_record_Identifier'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_record_Identifier'), 'subscriptions', ['record_Identifier'], unique=True)
    op.drop_column('subscriptions', 'stripe_checkout_session_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_index(op.f('ix_subscription_events_record_Identifier'), table_name='subscription_events')
    op.create_index(op.f('ix_subscription_events_record_Identifier'), 'subscription_events', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_refresh_tokens_record_Identifier'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_record_Identifier'), 'refresh_tokens', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_refill_dismissals_record_Identifier'), table_name='refill_dismissals')
    op.create_index(op.f('ix_refill_dismissals_record_Identifier'), 'refill_dismissals', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_plans_record_Identifier'), table_name='plans')
    op.create_index(op.f('ix_plans_record_Identifier'), 'plans', ['record_Identifier'], unique=True)
    op.drop_column('plans', 'stripe_price_id')
    op.drop_column('plans', 'stripe_product_id')
    op.drop_index(op.f('ix_medicines_record_Identifier'), table_name='medicines')
    op.create_index(op.f('ix_medicines_record_Identifier'), 'medicines', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_medicine_ndc_cache_record_Identifier'), table_name='medicine_ndc_cache')
    op.create_index(op.f('ix_medicine_ndc_cache_record_Identifier'), 'medicine_ndc_cache', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_medicine_inventory_record_Identifier'), table_name='medicine_inventory')
    op.create_index(op.f('ix_medicine_inventory_record_Identifier'), 'medicine_inventory', ['record_Identifier'], unique=True)
    op.drop_constraint(None, 'medical_store', type_='unique')
    op.drop_index(op.f('ix_medical_store_record_Identifier'), table_name='medical_store')
    op.create_index(op.f('ix_medical_store_record_Identifier'), 'medical_store', ['record_Identifier'], unique=True)
    op.drop_column('medical_store', 'stripe_customer_id')
    op.drop_column('medical_store', 'phone')
    op.drop_index(op.f('ix_invoices_record_Identifier'), table_name='invoices')
    op.create_index(op.f('ix_invoices_record_Identifier'), 'invoices', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_invoice_summaries_record_Identifier'), table_name='invoice_summaries')
    op.create_index(op.f('ix_invoice_summaries_record_Identifier'), 'invoice_summaries', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_invoice_line_items_record_Identifier'), table_name='invoice_line_items')
    op.create_index(op.f('ix_invoice_line_items_record_Identifier'), 'invoice_line_items', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_drug_reports_record_Identifier'), table_name='drug_reports')
    op.create_index(op.f('ix_drug_reports_record_Identifier'), 'drug_reports', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_documents_record_Identifier'), table_name='documents')
    op.create_index(op.f('ix_documents_record_Identifier'), 'documents', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_dispenses_record_Identifier'), table_name='dispenses')
    op.create_index(op.f('ix_dispenses_record_Identifier'), 'dispenses', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_activity_log_record_Identifier'), table_name='activity_log')
    op.create_index(op.f('ix_activity_log_record_Identifier'), 'activity_log', ['record_Identifier'], unique=True)
    op.drop_index(op.f('ix_subscription_payments_update_record_Identifier'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_status'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_record_Identifier'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_payment_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_medical_store_id'), table_name='subscription_payments')
    op.drop_index('ix_subpay_ms_id_status', table_name='subscription_payments')
    op.drop_table('subscription_payments')
    # ### end Alembic commands ###
