"""created report dispense models

Revision ID: 554d5947377e
Revises: c967a7f570eb
Create Date: 2026-04-18 16:23:06.834340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554d5947377e'
down_revision: Union[str, None] = 'c967a7f570eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=200), nullable=True),
    sa.Column('pharmacy_address', sa.String(length=400), nullable=True),
    sa.Column('pharmacy_phone', sa.String(length=30), nullable=True),
    sa.Column('pharmacy_fax', sa.String(length=30), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('report_from_date', sa.String(length=20), nullable=True),
    sa.Column('report_to_date', sa.String(length=20), nullable=True),
    sa.Column('grand_total_rx_count', sa.Integer(), nullable=True),
    sa.Column('grand_total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=300), nullable=False),
    sa.Column('ndc', sa.String(length=11), nullable=False),
    sa.Column('inventory_bucket', sa.String(length=100), nullable=True),
    sa.Column('lot_no_exp_date', sa.String(length=100), nullable=True),
    sa.Column('total_packs', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_rx_count', sa.Integer(), nullable=True),
    sa.Column('total_ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['drug_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_ndc'), 'medicines', ['ndc'], unique=False)
    op.create_index(op.f('ix_medicines_report_id'), 'medicines', ['report_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('qty_disp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('qty_ord', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('date_filled', sa.String(length=12), nullable=True),
    sa.Column('rx_no', sa.String(length=20), nullable=True),
    sa.Column('ref', sa.String(length=10), nullable=True),
    sa.Column('pat_name', sa.String(length=200), nullable=True),
    sa.Column('pat_addr', sa.Text(), nullable=True),
    sa.Column('pat_phone', sa.String(length=30), nullable=True),
    sa.Column('pres_name', sa.String(length=200), nullable=True),
    sa.Column('pres_addr', sa.Text(), nullable=True),
    sa.Column('pres_phone', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_code', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispenses_medicine_id'), 'dispenses', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_dispenses_rx_no'), 'dispenses', ['rx_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispenses_rx_no'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_medicine_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_medicines_report_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_ndc'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('drug_reports')
    # ### end Alembic commands ###
