"""renamed shop_owner to pharmacy_owner

Revision ID: 709930165713
Revises: 3bbfdcbb300c
Create Date: 2026-02-13 09:58:23.927304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '709930165713'
down_revision: Union[str, None] = '3bbfdcbb300c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_owner',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_pharmacy_owner_email'), 'pharmacy_owner', ['email'], unique=True)
    op.drop_index(op.f('ix_shopowner_email'), table_name='shopowner')
    op.drop_table('shopowner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopowner',
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('owner_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_shopowner_email'), 'shopowner', ['email'], unique=True)
    op.drop_index(op.f('ix_pharmacy_owner_email'), table_name='pharmacy_owner')
    op.drop_table('pharmacy_owner')
    # ### end Alembic commands ###
