"""Pharmacy model added -DB

Revision ID: 72b80522d6ac
Revises: d49bc0b2b1ee
Create Date: 2026-03-02 11:59:38.647325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b80522d6ac'
down_revision: Union[str, None] = 'd49bc0b2b1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
