"""extract_save_inventory_flow

Revision ID: 7fcbc56191d9
Revises: 
Create Date: 2026-06-12 22:35:16.350339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcbc56191d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_store',
    sa.Column('medical_store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='fk_pharmacy_user_id', onupdate='CASCADE', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('medical_store_id')
    )
    op.create_index(op.f('ix_medical_store_medical_store_id'), 'medical_store', ['medical_store_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PHARMACY_OWNER', 'TECHNICIAN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_key', sa.String(length=64), nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_key'), 'documents', ['doc_key'], unique=True)
    op.create_index(op.f('ix_documents_medical_store_id'), 'documents', ['medical_store_id'], unique=False)
    op.create_index(op.f('ix_documents_process_type'), 'documents', ['process_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_refresh_token_id'), 'refresh_tokens', ['refresh_token_id'], unique=False)
    op.create_table('drug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('report_from_date', sa.String(length=20), nullable=True),
    sa.Column('report_to_date', sa.String(length=20), nullable=True),
    sa.Column('grand_total_rx_count', sa.Integer(), nullable=True),
    sa.Column('grand_total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_reports_document_id'), 'drug_reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_drug_reports_medical_store_id'), 'drug_reports', ['medical_store_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('seller_address', sa.String(length=400), nullable=True),
    sa.Column('seller_phone', sa.String(length=30), nullable=True),
    sa.Column('seller_dea', sa.String(length=40), nullable=True),
    sa.Column('seller_permit', sa.String(length=40), nullable=True),
    sa.Column('seller_fed_id', sa.String(length=40), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.String(length=20), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('terms_of_payment', sa.String(length=100), nullable=True),
    sa.Column('your_order_number', sa.String(length=50), nullable=True),
    sa.Column('customer_number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_dea', sa.String(length=40), nullable=True),
    sa.Column('customer_state_reg', sa.String(length=40), nullable=True),
    sa.Column('bill_to_name', sa.String(length=200), nullable=True),
    sa.Column('bill_to_address', sa.String(length=400), nullable=True),
    sa.Column('ship_to_name', sa.String(length=200), nullable=True),
    sa.Column('ship_to_address', sa.String(length=400), nullable=True),
    sa.Column('remit_to_name', sa.String(length=200), nullable=True),
    sa.Column('remit_to_address', sa.String(length=400), nullable=True),
    sa.Column('remit_to_phone', sa.String(length=30), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_medical_store_id'), 'invoices', ['medical_store_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.String(length=20), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('raw_ndc', sa.String(length=30), nullable=True),
    sa.Column('ndc11', sa.String(length=11), nullable=True),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('lot_number', sa.String(length=40), nullable=True),
    sa.Column('orig_order_qty', sa.String(length=30), nullable=True),
    sa.Column('order_qty', sa.String(length=30), nullable=True),
    sa.Column('invoiced_qty', sa.String(length=30), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.String(length=30), nullable=True),
    sa.Column('extended_price', sa.String(length=30), nullable=True),
    sa.Column('awp', sa.String(length=30), nullable=True),
    sa.Column('note_code', sa.String(length=30), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('fda_package_ndc', sa.String(length=30), nullable=True),
    sa.Column('fda_ndc11', sa.String(length=11), nullable=True),
    sa.Column('dm_gtin', sa.String(length=20), nullable=True),
    sa.Column('dm_serial_number', sa.String(length=30), nullable=True),
    sa.Column('dm_expiration_date', sa.String(length=12), nullable=True),
    sa.Column('dm_lot_number', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_ndc11'), 'invoice_line_items', ['ndc11'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_upc'), 'invoice_line_items', ['upc'], unique=False)
    op.create_table('invoice_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_line_total', sa.String(length=30), nullable=True),
    sa.Column('fuel_surcharge', sa.String(length=30), nullable=True),
    sa.Column('sub_total', sa.String(length=30), nullable=True),
    sa.Column('tax', sa.String(length=30), nullable=True),
    sa.Column('grand_total', sa.String(length=30), nullable=True),
    sa.Column('total_due_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_summaries_invoice_id'), 'invoice_summaries', ['invoice_id'], unique=True)
    op.create_table('medicine_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medical_store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('last_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_store_id'], ['medical_store.medical_store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_store_id', 'code', name='uq_inventory_store_code')
    )
    op.create_index(op.f('ix_medicine_inventory_code'), 'medicine_inventory', ['code'], unique=False)
    op.create_index(op.f('ix_medicine_inventory_medical_store_id'), 'medicine_inventory', ['medical_store_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=300), nullable=False),
    sa.Column('ndc', sa.String(length=11), nullable=False),
    sa.Column('inventory_bucket', sa.String(length=100), nullable=True),
    sa.Column('lot_no_exp_date', sa.String(length=100), nullable=True),
    sa.Column('total_packs', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_rx_count', sa.Integer(), nullable=True),
    sa.Column('total_ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['drug_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_ndc'), 'medicines', ['ndc'], unique=False)
    op.create_index(op.f('ix_medicines_report_id'), 'medicines', ['report_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('qty_disp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('qty_ord', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('date_filled', sa.String(length=12), nullable=True),
    sa.Column('rx_no', sa.String(length=20), nullable=True),
    sa.Column('ref', sa.String(length=10), nullable=True),
    sa.Column('pat_name', sa.String(length=200), nullable=True),
    sa.Column('pat_addr', sa.Text(), nullable=True),
    sa.Column('pat_phone', sa.String(length=30), nullable=True),
    sa.Column('pres_name', sa.String(length=200), nullable=True),
    sa.Column('pres_addr', sa.Text(), nullable=True),
    sa.Column('pres_phone', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ins_code', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispenses_medicine_id'), 'dispenses', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_dispenses_rx_no'), 'dispenses', ['rx_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispenses_rx_no'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_medicine_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_medicines_report_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_ndc'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_medicine_inventory_medical_store_id'), table_name='medicine_inventory')
    op.drop_index(op.f('ix_medicine_inventory_code'), table_name='medicine_inventory')
    op.drop_table('medicine_inventory')
    op.drop_index(op.f('ix_invoice_summaries_invoice_id'), table_name='invoice_summaries')
    op.drop_table('invoice_summaries')
    op.drop_index(op.f('ix_invoice_line_items_upc'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_ndc11'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoices_medical_store_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_drug_reports_medical_store_id'), table_name='drug_reports')
    op.drop_index(op.f('ix_drug_reports_document_id'), table_name='drug_reports')
    op.drop_table('drug_reports')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_process_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_medical_store_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_key'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_medical_store_medical_store_id'), table_name='medical_store')
    op.drop_table('medical_store')
    # ### end Alembic commands ###
