"""add invoices reconciliation and limits

Revision ID: 832c883595c3
Revises: 9b2f7c1a4e3d
Create Date: 2026-05-27 23:20:02.063822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '832c883595c3'
down_revision: Union[str, None] = '9b2f7c1a4e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('invoices'):
        op.create_table('invoices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('source_filename', sa.String(length=255), nullable=True),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('seller_name', sa.String(length=200), nullable=True),
        sa.Column('seller_address', sa.String(length=400), nullable=True),
        sa.Column('seller_phone', sa.String(length=30), nullable=True),
        sa.Column('seller_dea', sa.String(length=40), nullable=True),
        sa.Column('seller_permit', sa.String(length=40), nullable=True),
        sa.Column('seller_fed_id', sa.String(length=40), nullable=True),
        sa.Column('invoice_number', sa.String(length=50), nullable=True),
        sa.Column('invoice_date', sa.String(length=20), nullable=True),
        sa.Column('order_number', sa.String(length=50), nullable=True),
        sa.Column('due_date', sa.String(length=20), nullable=True),
        sa.Column('terms_of_payment', sa.String(length=100), nullable=True),
        sa.Column('your_order_number', sa.String(length=50), nullable=True),
        sa.Column('customer_number', sa.String(length=50), nullable=True),
        sa.Column('customer_name', sa.String(length=200), nullable=True),
        sa.Column('customer_dea', sa.String(length=40), nullable=True),
        sa.Column('customer_state_reg', sa.String(length=40), nullable=True),
        sa.Column('bill_to_name', sa.String(length=200), nullable=True),
        sa.Column('bill_to_address', sa.String(length=400), nullable=True),
        sa.Column('ship_to_name', sa.String(length=200), nullable=True),
        sa.Column('ship_to_address', sa.String(length=400), nullable=True),
        sa.Column('remit_to_name', sa.String(length=200), nullable=True),
        sa.Column('remit_to_address', sa.String(length=400), nullable=True),
        sa.Column('remit_to_phone', sa.String(length=30), nullable=True),
        sa.Column('raw_payload', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('dispense_reconciliations'):
        op.create_table('dispense_reconciliations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('ndc11', sa.String(length=11), nullable=False),
        sa.Column('invoice_qty', sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column('dispensed_qty', sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column('remaining_qty', sa.Numeric(precision=12, scale=3), nullable=True),
        sa.ForeignKeyConstraint(['report_id'], ['drug_reports.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dispense_reconciliations_ndc11'), 'dispense_reconciliations', ['ndc11'], unique=False)
        op.create_index(op.f('ix_dispense_reconciliations_report_id'), 'dispense_reconciliations', ['report_id'], unique=False)

    if not inspector.has_table('invoice_line_items'):
        op.create_table('invoice_line_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('line', sa.String(length=20), nullable=True),
        sa.Column('item_code', sa.String(length=50), nullable=True),
        sa.Column('raw_ndc', sa.String(length=30), nullable=True),
        sa.Column('ndc11', sa.String(length=11), nullable=True),
        sa.Column('upc', sa.String(length=20), nullable=True),
        sa.Column('lot_number', sa.String(length=40), nullable=True),
        sa.Column('orig_order_qty', sa.String(length=30), nullable=True),
        sa.Column('order_qty', sa.String(length=30), nullable=True),
        sa.Column('invoiced_qty', sa.String(length=30), nullable=True),
        sa.Column('uom', sa.String(length=10), nullable=True),
        sa.Column('description', sa.String(length=400), nullable=True),
        sa.Column('size', sa.String(length=40), nullable=True),
        sa.Column('form', sa.String(length=20), nullable=True),
        sa.Column('unit_price', sa.String(length=30), nullable=True),
        sa.Column('extended_price', sa.String(length=30), nullable=True),
        sa.Column('awp', sa.String(length=30), nullable=True),
        sa.Column('note_code', sa.String(length=30), nullable=True),
        sa.Column('verification_required', sa.Boolean(), nullable=False),
        sa.Column('fda_package_ndc', sa.String(length=30), nullable=True),
        sa.Column('fda_ndc11', sa.String(length=11), nullable=True),
        sa.Column('dm_gtin', sa.String(length=20), nullable=True),
        sa.Column('dm_serial_number', sa.String(length=30), nullable=True),
        sa.Column('dm_expiration_date', sa.String(length=12), nullable=True),
        sa.Column('dm_lot_number', sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
        op.create_index(op.f('ix_invoice_line_items_ndc11'), 'invoice_line_items', ['ndc11'], unique=False)
        op.create_index(op.f('ix_invoice_line_items_upc'), 'invoice_line_items', ['upc'], unique=False)

    if not inspector.has_table('invoice_summaries'):
        op.create_table('invoice_summaries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('order_line_total', sa.String(length=30), nullable=True),
        sa.Column('fuel_surcharge', sa.String(length=30), nullable=True),
        sa.Column('sub_total', sa.String(length=30), nullable=True),
        sa.Column('tax', sa.String(length=30), nullable=True),
        sa.Column('grand_total', sa.String(length=30), nullable=True),
        sa.Column('total_due_by', sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_invoice_summaries_invoice_id'), 'invoice_summaries', ['invoice_id'], unique=True)
    # NOTE: Skipping unrelated drops/alterations for legacy tables to avoid FK issues.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Skipping legacy table restores for address/otp/transfer/pharmacy.
    op.drop_index(op.f('ix_invoice_summaries_invoice_id'), table_name='invoice_summaries')
    op.drop_table('invoice_summaries')
    op.drop_index(op.f('ix_invoice_line_items_upc'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_ndc11'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_dispense_reconciliations_report_id'), table_name='dispense_reconciliations')
    op.drop_index(op.f('ix_dispense_reconciliations_ndc11'), table_name='dispense_reconciliations')
    op.drop_table('dispense_reconciliations')
    op.drop_table('invoices')
    # ### end Alembic commands ###
