"""Add ownership transfer and OTP tables

Revision ID: 9b2f7c1a4e3d
Revises: 470fc37b5f75
Create Date: 2026-04-29 09:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2f7c1a4e3d'
down_revision: Union[str, None] = '470fc37b5f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pharmacy_ownership_transfer',
        sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('pharmacy_id', sa.Integer(), nullable=False),
        sa.Column('current_owner_id', sa.Integer(), nullable=False),
        sa.Column('new_owner_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('ACTIVE', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='ownershiptransferstatus'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('rejected_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['current_owner_id'],
            ['user.user_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['new_owner_id'],
            ['user.user_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['pharmacy_id'],
            ['pharmacy.pharmacy_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('transfer_id'),
    )
    op.create_index(
        op.f('ix_pharmacy_ownership_transfer_transfer_id'),
        'pharmacy_ownership_transfer',
        ['transfer_id'],
        unique=False,
    )
    op.create_table(
        'otp_code',
        sa.Column('otp_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'purpose',
            sa.Enum('TRANSFER_CREATE', 'TRANSFER_ACCEPT', name='otppurpose'),
            nullable=False,
        ),
        sa.Column('code_hash', sa.String(length=255), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('max_attempts', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('pharmacy_id', sa.Integer(), nullable=True),
        sa.Column('transfer_request_id', sa.Integer(), nullable=True),
        sa.Column('new_owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['new_owner_id'],
            ['user.user_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['pharmacy_id'],
            ['pharmacy.pharmacy_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['transfer_request_id'],
            ['pharmacy_ownership_transfer.transfer_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.user_id'],
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('otp_id'),
    )
    op.create_index(op.f('ix_otp_code_otp_id'), 'otp_code', ['otp_id'], unique=False)
    op.create_index(op.f('ix_otp_code_user_id'), 'otp_code', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_code_user_id'), table_name='otp_code')
    op.drop_index(op.f('ix_otp_code_otp_id'), table_name='otp_code')
    op.drop_table('otp_code')
    op.drop_index(op.f('ix_pharmacy_ownership_transfer_transfer_id'), table_name='pharmacy_ownership_transfer')
    op.drop_table('pharmacy_ownership_transfer')
    # ### end Alembic commands ###
