"""Added AutoIncrement and unique in PK of pharmacy_owner - DB

Revision ID: a7bee66c8510
Revises: 709930165713
Create Date: 2026-02-16 10:46:35.474686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bee66c8510'
down_revision: Union[str, None] = '709930165713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pharmacy_owner_owner_id'), 'pharmacy_owner', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_owner_owner_id'), table_name='pharmacy_owner')
    # ### end Alembic commands ###
