"""Address added

Revision ID: afb7dbc843eb
Revises: c967a7f570eb
Create Date: 2026-04-28 10:58:08.268643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afb7dbc843eb'
down_revision: Union[str, None] = 'c967a7f570eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicines_ndc'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_report_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_dispenses_medicine_id'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_rx_no'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_table('drug_reports')
    op.add_column('pharmacy', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pharmacy', 'address', ['address_id'], ['address_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('pharmacy', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'pharmacy', type_='foreignkey')
    op.drop_column('pharmacy', 'address_id')
    op.create_table('drug_reports',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('pharmacy_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pharmacy_address', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('pharmacy_phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('pharmacy_fax', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('report_date', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('report_from_date', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('report_to_date', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('grand_total_rx_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grand_total_price', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('grand_total_cost', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('dispenses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('medicine_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('qty_disp', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('qty_ord', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('days_supply', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_filled', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('rx_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ref', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('pat_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pat_addr', mysql.TEXT(), nullable=True),
    sa.Column('pat_phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('pres_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pres_addr', mysql.TEXT(), nullable=True),
    sa.Column('pres_phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('ins_paid', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('ins_code', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('dispenses_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_dispenses_rx_no'), 'dispenses', ['rx_no'], unique=False)
    op.create_index(op.f('ix_dispenses_medicine_id'), 'dispenses', ['medicine_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('drug_name', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('ndc', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('inventory_bucket', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lot_no_exp_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_packs', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('total_rx_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_ins_paid', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_price', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['drug_reports.id'], name=op.f('medicines_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_medicines_report_id'), 'medicines', ['report_id'], unique=False)
    op.create_index(op.f('ix_medicines_ndc'), 'medicines', ['ndc'], unique=False)
    # ### end Alembic commands ###
