"""added reletationship between User(Technician) and Pharmacy issue solved-DB

Revision ID: c967a7f570eb
Revises: 2a898550855b
Create Date: 2026-03-13 15:33:43.930944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c967a7f570eb'
down_revision: Union[str, None] = '2a898550855b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    # ### end Alembic commands ###
