"""Added enums type for role - DB

Revision ID: dd9a418b455e
Revises: a7bee66c8510
Create Date: 2026-02-18 10:08:48.435436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9a418b455e'
down_revision: Union[str, None] = 'a7bee66c8510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_owner', sa.Column('role', sa.Enum('PHARMACY_OWNER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_owner', 'role')
    # ### end Alembic commands ###
