"""Update-2 enums type for role - DB

Revision ID: e77a2ed18983
Revises: f9846a6f389c
Create Date: 2026-02-18 10:10:21.408783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77a2ed18983'
down_revision: Union[str, None] = 'f9846a6f389c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
