"""Update-1 enums type for role - DB

Revision ID: f9846a6f389c
Revises: dd9a418b455e
Create Date: 2026-02-18 10:09:58.056623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9846a6f389c'
down_revision: Union[str, None] = 'dd9a418b455e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
